--STAGING TABLES
CREATE TABLE CLIENT_STG (
    CLIENT_STG_ID VARCHAR2(16) PRIMARY KEY
    --could add a lot more here, but not needed for short demo
);

CREATE TABLE INVOICE_STG (
    INVOICE_STG_ID VARCHAR2(16),
    CLIENT_ID VARCHAR2(16),
    INVOICE_AMT NUMBER(50),
    INVOICE_AMT_SUB_FLG BOOLEAN,
    INVOICE_TYPE VARCHAR2(2),
    INVOICE_TYPE_SUB_FLG BOOLEAN,
    INVOICE_STATUS VARCHAR2(1),
    FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT_STG(CLIENT_STG_ID),
    PRIMARY KEY(INVOICE_STG_ID, CLIENT_ID)
);

--FINAL TABLES
CREATE TABLE CLIENT (
    CLIENT_ID VARCHAR2(16) PRIMARY KEY

);

CREATE TABLE INVOICE (
    INVOICE_ID VARCHAR2(16) PRIMARY KEY,
    CLIENT_ID VARCHAR2(16),
    INVOICE_AMT NUMBER(50),
    INVOICE_TYPE VARCHAR2(2),
    FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)
);

--REFERENCE TABLES
CREATE TABLE INVOICE_TYPE_REF (
    INVOICE_TYPE_REF_ID VARCHAR2(2) PRIMARY KEY,
    DESCR VARCHAR2(200),
    MAX_AMT NUMBER(50)
);

--SEQUENCES
CREATE SEQUENCE INVOICE_STG_ID_SEQ;


INSERT INTO INVOICE_TYPE_REF (INVOICE_TYPE_REF_ID, DESCR, MAX_AMT)
VALUES 
('LG', 'LEGAL EXPENSE', 10000),
('PR', 'PAYROLL', 1000000),
('SB', 'SUBSCRIPTION', 1000),
('AW', 'AMAZON WEB SERVICE', 10000000);

INSERT INTO CLIENT_STG (CLIENT_STG_ID) VALUES ('1'),('2'),('3');

INSERT INTO CLIENT (CLIENT_ID) VALUES ('1'),('2'),('3');