
--INSERT INTO CLIENT_STG (CLIENT_STG_ID)
--VALUES ('1');

--INSERT INTO CLIENT (CLIENT_ID)
--VALUES ('1');

INSERT INTO INVOICE_STG (INVOICE_STG_ID, CLIENT_ID, INVOICE_AMT, INVOICE_AMT_SUB_FLG, INVOICE_TYPE, INVOICE_TYPE_SUB_FLG, INVOICE_STATUS)
VALUES
(1,'1',100000,TRUE,'LG',TRUE,'P');

